[{"name": "test.test_bicycle_timeseries.BicycleTimeseries.test_calls", "status": "failed", "message": "Expected 'bicycle_timeseries' to have been called once. Called 0 times.", "passed": false, "points": ["p05-08.1"], "backtrace": ["  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 615, in run\n    testMethod()\n", "  File \"C:\\Users\\koske\\Documents\\Koodit\\hy-data-analysis-with-python-summer-2019\\part05-e08_bicycle_timeseries\\test\\test_bicycle_timeseries.py\", line 57, in test_calls\n    pbts.assert_called_once()\n", "  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\mock.py\", line 810, in assert_called_once\n    raise AssertionError(msg)\n"]}, {"name": "test.test_bicycle_timeseries.BicycleTimeseries.test_columns", "status": "failed", "message": "\nArrays are not equal\nIncorrect columns!\n(shapes (26,), (20,) mismatch)\n x: array(['Weekday', 'Day', 'Month', 'Year', 'Hour', 'Min', 'Auroransilta',\n       'Eteläesplanadi', 'Huopalahti (asema)',\n       'Kaisaniemi/Eläintarhanlahti', 'Kaivokatu', 'Kulosaaren silta et.',...\n y: array(['Auroransilta', 'Eteläesplanadi', 'Huopalahti (asema)',\n       'Kaisaniemi/Eläintarhanlahti', 'Kaivokatu', 'Kulosaaren silta et.',\n       'Kulosaaren silta po. ', 'Kuusisaarentie', 'Käpylä, Pohjoisbaana',...", "passed": false, "points": ["p05-08.1"], "backtrace": ["  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 615, in run\n    testMethod()\n", "  File \"C:\\Users\\koske\\Documents\\Koodit\\hy-data-analysis-with-python-summer-2019\\part05-e08_bicycle_timeseries\\test\\test_bicycle_timeseries.py\", line 41, in test_columns\n    np.testing.assert_array_equal(self.df.columns, cols, err_msg=\"Incorrect columns!\")\n", "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\testing\\_private\\utils.py\", line 904, in assert_array_equal\n    verbose=verbose, header='Arrays are not equal')\n", "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\testing\\_private\\utils.py\", line 752, in assert_array_compare\n    raise AssertionError(msg)\n"]}, {"name": "test.test_bicycle_timeseries.BicycleTimeseries.test_index", "status": "passed", "message": "", "passed": true, "points": ["p05-08.1"], "backtrace": []}, {"name": "test.test_bicycle_timeseries.BicycleTimeseries.test_shape", "status": "failed", "message": "Tuples differ: (37128, 26) != (37128, 20)\n\nFirst differing element 1:\n26\n20\n\n- (37128, 26)\n?          ^\n\n+ (37128, 20)\n?          ^\n : Incorrect shape!", "passed": false, "points": ["p05-08.1"], "backtrace": ["  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 615, in run\n    testMethod()\n", "  File \"C:\\Users\\koske\\Documents\\Koodit\\hy-data-analysis-with-python-summer-2019\\part05-e08_bicycle_timeseries\\test\\test_bicycle_timeseries.py\", line 30, in test_shape\n    self.assertEqual(self.df.shape, (37128, 20), msg=\"Incorrect shape!\")\n", "  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 839, in assertEqual\n    assertion_func(first, second, msg=msg)\n", "  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 1056, in assertTupleEqual\n    self.assertSequenceEqual(tuple1, tuple2, msg, seq_type=tuple)\n", "  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 1027, in assertSequenceEqual\n    self.fail(msg)\n", "  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 680, in fail\n    raise self.failureException(msg)\n"]}]